export const gameData = {
  gameInfo: {
    GameID: '113710',
    GameStatStatus: '3',
    SportID: '1',
    SportName: 'Football',
    GameSeason: '2018',
    GameAwayTeamID: '540',
    awayTeamName: 'Waco La Vega',
    awayTeamCode: 'WL',
    GameHomeTeamID: '881',
    homeTeamName: 'Argyle',
    homeTeamCode: 'AY',
    GameDate: '2018-12-07',
    GameTime: '19:00:00',
    GameMeetName: '',
    GameIsDistrict: '0',
    GameIsPlayoff: '1',
    GamePlayoffID: '117',
    PlayoffName: 'UIL',
    GamePlayoffRound: 'Regional Final',
    GameIsTournament: '0',
    GameTournamentID: '0',
    TournamentName: null,
    GameTournamentRound: '',
    GameMeetSite: '0',
    GameLocation: '3735',
    GameScoreIsFinal: '1',
    GameIsLiveScoring: '1',
    GameStatsFinal: '0',
    GameIsNeutral: '1',
    GameProjectedUpset: '0',
    NeutralSite: 'Midlothian ISD Multi-Purpose Stadium',
    GameStatsDateTimeModified: '2018-12-07 21:39:55',
    GamePeriod: '',
    GamePeriodTime: '',
    GameUpdate: '0',
    GameHasUpdate: '0',
  },
  away: {
    team: {
      TeamID: '540',
      TeamName: 'Waco La Vega',
      TeamCode: 'WL',
      TeamNickname: '',
      TeamAbbrevSmall: 'WL',
      TeamAbbrevMedium: 'La Vega',
      TeamAbbrevLarge: 'Waco La Vega',
      TeamHeadCoach: '',
      TeamAssistantCoaches: '',
      TeamCoachWorkEmail: '',
      TeamCoachWorkPhone: '',
      TeamCoachCellPhone: '',
      SportID: '1',
      SportName: 'Football',
      DistrictID: '66',
      DistrictName: '19-3A',
      ClassID: '7',
      ClassName: 'CLASS 3A',
      ConferenceID: null,
      ConferenceName: null,
      SchoolID: '58',
      SchoolName: 'Waco La Vega',
      SchoolCode: 'LAV',
      SchoolAbbrevSmall: 'WL',
      SchoolAbbrevMedium: 'La Vega',
      SchoolAbbrevLarge: 'Waco La Vega',
      SchoolAddress: '508 Young',
      SchoolCity: 'Waco',
      SchoolState: 'TX',
      SchoolZip: '75202',
      SchoolPhone: '',
      SchoolFax: '',
      SchoolEmailAddress: '',
      SchoolURL: '',
      SchoolLatitude: '',
      SchoolLongitude: '',
    },
    roster: [{
      PlayerID: '12305',
      PlayerFirstName: 'Robert',
      PlayerLastName: 'Allen',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '64',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25191',
      PlayerFirstName: 'James',
      PlayerLastName: 'Baggett',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '59',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12308',
      PlayerFirstName: 'Andrew',
      PlayerLastName: 'Brown',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '68',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12309',
      PlayerFirstName: 'Damion',
      PlayerLastName: 'Brown',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '72',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25193',
      PlayerFirstName: 'Eric',
      PlayerLastName: 'Brown',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '66',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12322',
      PlayerFirstName: 'Reginald',
      PlayerLastName: 'Brown',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '50',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12295',
      PlayerFirstName: 'Jacob',
      PlayerLastName: 'Bryant',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '14',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12316',
      PlayerFirstName: 'Anthony',
      PlayerLastName: 'Burns',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '21',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12280',
      PlayerFirstName: 'Demicco',
      PlayerLastName: 'Chambliss',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '2',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12321',
      PlayerFirstName: 'Ian',
      PlayerLastName: 'Chavez',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '31',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12304',
      PlayerFirstName: 'JaCorrey',
      PlayerLastName: 'Coaster',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '35',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12294',
      PlayerFirstName: 'Javion',
      PlayerLastName: 'Crosson',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '13',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12314',
      PlayerFirstName: 'Elisha',
      PlayerLastName: 'Cummings',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12300',
      PlayerFirstName: 'Ivan',
      PlayerLastName: 'Curl',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '19',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12286',
      PlayerFirstName: "Sol'dreveon",
      PlayerLastName: 'Degrate',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '7',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25194',
      PlayerFirstName: 'Gavin',
      PlayerLastName: 'Donaldson',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '75',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12320',
      PlayerFirstName: 'Trevonte',
      PlayerLastName: 'Garrett',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '33',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12283',
      PlayerFirstName: 'Amari',
      PlayerLastName: 'Gibson',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25197',
      PlayerFirstName: "Ke'erran",
      PlayerLastName: 'Ginn',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '92',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25201',
      PlayerFirstName: "Ke'erran",
      PlayerLastName: 'Ginn',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25200',
      PlayerFirstName: "Ke'errian",
      PlayerLastName: 'Ginn',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12301',
      PlayerFirstName: 'Tyquavis',
      PlayerLastName: 'Goode',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12279',
      PlayerFirstName: 'Josh',
      PlayerLastName: 'Hamilton',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '1',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '21936',
      PlayerFirstName: 'D.',
      PlayerLastName: 'Hayes',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '99',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12290',
      PlayerFirstName: 'DeMarrquese',
      PlayerLastName: 'Hayes',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '10',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25198',
      PlayerFirstName: 'Vincent',
      PlayerLastName: 'Henderson',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '94',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12284',
      PlayerFirstName: 'Javon',
      PlayerLastName: 'Iglehart',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '5',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12285',
      PlayerFirstName: "Jai'brian",
      PlayerLastName: "Jai'brian Bouye",
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25192',
      PlayerFirstName: 'Zamarion',
      PlayerLastName: 'Johnson',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '62',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12317',
      PlayerFirstName: 'Ricky',
      PlayerLastName: 'Jones',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '27',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25196',
      PlayerFirstName: 'Chris',
      PlayerLastName: 'Kelley',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '77',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25195',
      PlayerFirstName: 'Jaron',
      PlayerLastName: 'Levingston',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '76',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '22354',
      PlayerFirstName: 'Jesse',
      PlayerLastName: 'Majors-Sterling',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '24',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12307',
      PlayerFirstName: 'Jaelyn',
      PlayerLastName: 'Maladdie',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '55',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12289',
      PlayerFirstName: 'Quintaveon',
      PlayerLastName: 'Mason',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '9',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12288',
      PlayerFirstName: 'Zakevian',
      PlayerLastName: 'Mayberry',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12287',
      PlayerFirstName: 'Jordan',
      PlayerLastName: 'Mckinney',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '8',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12318',
      PlayerFirstName: 'Jordan',
      PlayerLastName: 'Morgan',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '30',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '22355',
      PlayerFirstName: 'Eric',
      PlayerLastName: 'Ramirez',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '24569',
      PlayerFirstName: 'Raul',
      PlayerLastName: 'Ramirez',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '44',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12297',
      PlayerFirstName: 'Ara',
      PlayerLastName: 'Rauls',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '16',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12315',
      PlayerFirstName: 'Keyon',
      PlayerLastName: 'Reese',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '22',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '15296',
      PlayerFirstName: 'John',
      PlayerLastName: 'Richards',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '17',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12299',
      PlayerFirstName: 'Jaylon',
      PlayerLastName: 'Ridge',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '18',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25199',
      PlayerFirstName: 'Raeshawn',
      PlayerLastName: 'Roberts',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '98',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12296',
      PlayerFirstName: 'Jared',
      PlayerLastName: 'Rogers',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '15',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12313',
      PlayerFirstName: 'Jordan',
      PlayerLastName: 'Rogers',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '20',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12319',
      PlayerFirstName: 'Manuel',
      PlayerLastName: 'Ruiz',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12302',
      PlayerFirstName: 'Michael',
      PlayerLastName: 'Sheppard',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '27',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12306',
      PlayerFirstName: 'Eric',
      PlayerLastName: 'Speight',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '52',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '21937',
      PlayerFirstName: 'Team',
      PlayerLastName: 'Stat',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12291',
      PlayerFirstName: 'Donta',
      PlayerLastName: 'Stuart',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '11',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12310',
      PlayerFirstName: 'DeTreveon',
      PlayerLastName: 'Thompson',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '97',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12293',
      PlayerFirstName: 'Eddie',
      PlayerLastName: 'Toca',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12292',
      PlayerFirstName: 'Taequan',
      PlayerLastName: 'Tyler',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '12',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '25190',
      PlayerFirstName: 'Vernon ',
      PlayerLastName: 'Walker',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '54',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '15292',
      PlayerFirstName: "Jar'Quae",
      PlayerLastName: 'Walton',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '6',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12282',
      PlayerFirstName: 'Daylon',
      PlayerLastName: 'Williams',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '4',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12303',
      PlayerFirstName: 'Caleb',
      PlayerLastName: 'Wright',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '34',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '12281',
      PlayerFirstName: 'Malachi',
      PlayerLastName: 'Wright',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '3',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }],
    seasonstats: {
      Win: '4',
      Loss: '1',
      TotalYards: '2613',
      AverageOffensiveYards: 522.6,
      AverageDefensiveYards: 253.4,
      FirstDowns: '102',
      RushingAttempts: '241',
      RushingYards: '2162',
      PassCompletions: '25',
      PassAttempts: '45',
      PassingInterceptions: '1',
      PassingYards: '451',
      PassCompletionPercentage: 55.56,
      Punts: '20',
      PuntingYards: '576',
      PuntingAverage: '28.8',
      Fumbles: '6',
      FumblesLost: '2',
      Penalties: '39',
      PenaltyYards: '363',
      AverageRush: 8.97,
    },
  },
  home: {
    team: {
      TeamID: '881',
      TeamName: 'Argyle',
      TeamCode: 'AY',
      TeamNickname: 'Eagles',
      TeamAbbrevSmall: '',
      TeamAbbrevMedium: '',
      TeamAbbrevLarge: '',
      TeamHeadCoach: 'Todd Rodgers',
      TeamAssistantCoaches: '',
      TeamCoachWorkEmail: 'trodgers@argyleisd.com',
      TeamCoachWorkPhone: '940-262-7777 ext. 7001',
      TeamCoachCellPhone: '940-465-4783',
      SportID: '1',
      SportName: 'Football',
      DistrictID: '357',
      DistrictName: '7-4A DIV. 1',
      ClassID: '12',
      ClassName: 'CLASS 4A DIV. 1',
      ConferenceID: null,
      ConferenceName: null,
      SchoolID: '471',
      SchoolName: 'Argyle',
      SchoolCode: 'ARG',
      SchoolAbbrevSmall: 'ARG',
      SchoolAbbrevMedium: 'Argyle',
      SchoolAbbrevLarge: 'Argyle',
      SchoolAddress: '800 Eagle Drive',
      SchoolCity: 'Argyle',
      SchoolState: 'TX',
      SchoolZip: '76266',
      SchoolPhone: '',
      SchoolFax: '',
      SchoolEmailAddress: '',
      SchoolURL: 'http:\/\/www.esc11.net\/schools\/argyle\/argyle',
      SchoolLatitude: '33.2067059',
      SchoolLongitude: '-97.140833',
    },
    roster: [{
      PlayerID: '3049',
      PlayerFirstName: 'Wyatt',
      PlayerLastName: 'Allcorn',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '40',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3034',
      PlayerFirstName: 'Braden',
      PlayerLastName: 'Baker',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '20',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3063',
      PlayerFirstName: 'Landry',
      PlayerLastName: 'Barnett',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '55',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3052',
      PlayerFirstName: 'Christian',
      PlayerLastName: 'Burkhart',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '43',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3024',
      PlayerFirstName: 'Tito',
      PlayerLastName: 'Byce',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '9',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3018',
      PlayerFirstName: 'Dillon',
      PlayerLastName: 'Carter',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '3',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3017',
      PlayerFirstName: 'Hayden',
      PlayerLastName: 'Clearman',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '2',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3043',
      PlayerFirstName: 'Colin',
      PlayerLastName: 'Crawford',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '30',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3051',
      PlayerFirstName: 'John',
      PlayerLastName: 'Crowder',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '42',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3059',
      PlayerFirstName: 'Calvin',
      PlayerLastName: 'Davee',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '51',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '21013',
      PlayerFirstName: 'CULLEN',
      PlayerLastName: 'DAVEE',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '22376',
      PlayerFirstName: 'Cullen',
      PlayerLastName: 'Davee',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3020',
      PlayerFirstName: 'Brenden',
      PlayerLastName: 'Dixon',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '5',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3030',
      PlayerFirstName: 'Carter',
      PlayerLastName: 'Dodson',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '16',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3061',
      PlayerFirstName: 'Naton',
      PlayerLastName: 'Edwards',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '53',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3046',
      PlayerFirstName: 'Davis',
      PlayerLastName: 'Elsey',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '35',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3040',
      PlayerFirstName: 'Luke',
      PlayerLastName: 'Farris',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '26',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3056',
      PlayerFirstName: 'Elias',
      PlayerLastName: 'Garcia',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '47',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3021',
      PlayerFirstName: 'Alex',
      PlayerLastName: 'Gonzales',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '6',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3064',
      PlayerFirstName: 'Carson',
      PlayerLastName: 'Hackney',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '58',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3041',
      PlayerFirstName: 'Luke',
      PlayerLastName: 'Hamblin',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '27',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3037',
      PlayerFirstName: 'Riley',
      PlayerLastName: 'Hartman',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '23',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3078',
      PlayerFirstName: 'Micah',
      PlayerLastName: 'Hiter',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '79',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3027',
      PlayerFirstName: 'Bo',
      PlayerLastName: 'Hogeboom',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '13',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3066',
      PlayerFirstName: 'Connor',
      PlayerLastName: 'Homeyer',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '63',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3033',
      PlayerFirstName: 'Connor',
      PlayerLastName: 'Kilgore',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '19',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3038',
      PlayerFirstName: 'Cole',
      PlayerLastName: 'Kirkpatrick',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '24',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3048',
      PlayerFirstName: 'John',
      PlayerLastName: 'Krzysiak',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '37',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3060',
      PlayerFirstName: 'Brandon',
      PlayerLastName: 'Lancaster',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '52',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3019',
      PlayerFirstName: 'Noah',
      PlayerLastName: 'Lang',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '4',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3028',
      PlayerFirstName: 'Hunter',
      PlayerLastName: 'Martindale',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '14',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3067',
      PlayerFirstName: 'CJ',
      PlayerLastName: 'Massey',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '64',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '20989',
      PlayerFirstName: 'WARD',
      PlayerLastName: 'MCCOLLUM',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '22374',
      PlayerFirstName: 'Ward',
      PlayerLastName: 'McCollum',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3025',
      PlayerFirstName: 'Caden',
      PlayerLastName: 'Merka',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '10',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3042',
      PlayerFirstName: 'Blake',
      PlayerLastName: 'Michels',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '28',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3062',
      PlayerFirstName: 'Brandon',
      PlayerLastName: 'Michels',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '54',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3054',
      PlayerFirstName: 'Colby',
      PlayerLastName: 'Morse',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '45',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3029',
      PlayerFirstName: 'Caleb',
      PlayerLastName: 'Murdock',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '15',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3050',
      PlayerFirstName: 'Nico',
      PlayerLastName: 'Patrick',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '41',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3068',
      PlayerFirstName: 'Garrett',
      PlayerLastName: 'Peck',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '67',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3039',
      PlayerFirstName: 'Chase',
      PlayerLastName: 'Petter',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '25',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3071',
      PlayerFirstName: 'Ross',
      PlayerLastName: 'Picquet',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '71',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3074',
      PlayerFirstName: 'Jayton',
      PlayerLastName: 'Polley',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '74',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3036',
      PlayerFirstName: 'Ethan',
      PlayerLastName: 'Pruner',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '22',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3031',
      PlayerFirstName: 'Blake',
      PlayerLastName: 'Ramsey',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '17',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3045',
      PlayerFirstName: 'Mason',
      PlayerLastName: 'Ramsey',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '33',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3073',
      PlayerFirstName: 'Caden',
      PlayerLastName: 'Reeves',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '73',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3055',
      PlayerFirstName: 'Braiden',
      PlayerLastName: 'Rexroat',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '46',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3076',
      PlayerFirstName: 'Austin',
      PlayerLastName: 'Rivero',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '76',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3032',
      PlayerFirstName: 'Frank',
      PlayerLastName: 'Russell',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '18',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3022',
      PlayerFirstName: 'Adam',
      PlayerLastName: 'Schleder',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '7',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3044',
      PlayerFirstName: 'Grant',
      PlayerLastName: 'Shaw',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '32',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3065',
      PlayerFirstName: 'Ryan',
      PlayerLastName: 'Shobe',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '62',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3077',
      PlayerFirstName: 'Blake',
      PlayerLastName: 'Spence',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '78',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3057',
      PlayerFirstName: 'Tanner',
      PlayerLastName: 'Starkey',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '48',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '15301',
      PlayerFirstName: 'Team',
      PlayerLastName: 'Stat',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '21014',
      PlayerFirstName: 'ZACH',
      PlayerLastName: 'STEWART',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '22380',
      PlayerFirstName: 'Zach',
      PlayerLastName: 'Stewart',
      PlayerYear: '',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3058',
      PlayerFirstName: 'Blake',
      PlayerLastName: 'Sullivan',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '50',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3023',
      PlayerFirstName: 'Jackson',
      PlayerLastName: 'Sullivan',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '8',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3035',
      PlayerFirstName: 'Jake',
      PlayerLastName: 'Sullivan',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '21',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3070',
      PlayerFirstName: 'Garrett',
      PlayerLastName: 'Thomas',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '70',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3075',
      PlayerFirstName: 'Jack',
      PlayerLastName: 'Tucker',
      PlayerYear: 'Sophomore',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '75',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3069',
      PlayerFirstName: 'Colton',
      PlayerLastName: 'Van Alstine',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '68',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3053',
      PlayerFirstName: 'Tate',
      PlayerLastName: 'Van Poppel',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '44',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3026',
      PlayerFirstName: 'Brandon',
      PlayerLastName: 'White',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '11',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3072',
      PlayerFirstName: 'Preston',
      PlayerLastName: 'Wilson',
      PlayerYear: 'Senior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '72',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }, {
      PlayerID: '3047',
      PlayerFirstName: 'Jake',
      PlayerLastName: 'Woelfel',
      PlayerYear: 'Junior',
      PlayerHeightFeet: '0',
      PlayerHeightInches: '0',
      PlayerWeight: '',
      TeamRosterPlayerNumber: '36',
      TeamRosterPosition: '',
      TeamRosterAdditionalPositions: '',
    }],
    seasonstats: {
      Win: '13',
      Loss: '1',
      TotalYards: '6621',
      AverageOffensiveYards: 472.93,
      AverageDefensiveYards: 284.29,
      FirstDowns: '309',
      RushingAttempts: '506',
      RushingYards: '2752',
      PassCompletions: '231',
      PassAttempts: '405',
      PassingInterceptions: '10',
      PassingYards: '3869',
      PassCompletionPercentage: 57.04,
      Punts: '40',
      PuntingYards: '1610',
      PuntingAverage: '40.25',
      Fumbles: '28',
      FumblesLost: '10',
      Penalties: '93',
      PenaltyYards: '807',
      AverageRush: 5.44,
    },
  },
};

export const scoreUpdate = {
  gameData: {
    GameID: '113710',
    GameScoreIsFinal: '1',
    GameStatStatus: '3',
    GameStatsFinal: '0',
    GameStatsDateTimeModified: '2018-12-07 21:39:55',
  },
  pbpData: {
    GameID: '113710',
    Season: '2018',
    AwayTeamCode: 'WL',
    AwayTeamName: 'Waco La Vega',
    HomeTeamCode: 'AY',
    HomeTeamName: 'Argyle',
    SummaryQuarters: {
      '1st Quarter': {
        BallPossession: {
          1: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: 0,
            HomeScorePrev: 0,
            AwayScoreCurr: 0,
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Start of Quarter',
                SummaryDescription: 'Start of 1st Quarter',
              },
            },
          },
          2: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: 0,
            HomeScorePrev: 0,
            AwayScoreCurr: 0,
            HomeScoreCurr: 0,
            Records: {
              1: {
                TimeLeft: '11:56 left in 1st Quarter.',
                SummaryEvent: '',
                SummaryType: 'Kickoff Return',
                SummaryDescription: 'Adam Schleder returns kick 10 yards.',
              },
              2: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'AY penalized 5 yards.',
              },
              3: {
                SummaryEvent: '1st down and 15 at AY 16',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Alex Gonzales for 27 yards to AY 43. FIRST DOWN.',
              },
              4: {
                SummaryEvent: '1st down and 10 at AY 43',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Dillon Carter for 0 yards to AY 43.',
              },
              5: {
                SummaryEvent: '2nd down and 10 at AY 43',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 2 yards to AY 45.',
              },
              6: {
                SummaryEvent: '3rd down and 8 at AY 45',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Cole Kirkpatrick for 20 yards to WL 35. FIRST DOWN.',
              },
              7: {
                SummaryEvent: '1st down and 10 at WL 35',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 3 yards to WL 32.',
              },
              8: {
                SummaryEvent: '2nd down and 7 at WL 32',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 6 yards to WL 26.',
              },
              9: {
                SummaryEvent: '3rd down and 1 at WL 26',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              10: {
                SummaryEvent: '4th down and 1 at WL 26',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 2 yards to WL 24. FIRST DOWN.',
              },
              11: {
                SummaryEvent: '1st down and 10 at WL 24',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              12: {
                SummaryEvent: '2nd down and 10 at WL 24',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 1 yards to WL 23.',
              },
              13: {
                SummaryEvent: '3rd down and 9 at WL 23',
                SummaryType: 'Run',
                SummaryDescription: 'Alex Gonzales rush for 1 yards to WL 22.',
              },
              14: {
                TimeLeft: '7:50 left in 1st Quarter.',
                SummaryEvent: '4th down and 8 at WL 22',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
            },
          },
          3: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: 0,
            HomeScorePrev: 0,
            AwayScoreCurr: '7',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 22',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -3 yards to WL 19.',
              },
              2: {
                SummaryEvent: '2nd down and 13 at WL 19',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 1 yards to WL 20.',
              },
              3: {
                SummaryEvent: '3rd down and 12 at WL 20',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Ara Rauls pass incomplete.',
              },
              4: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 5 yards.',
              },
              5: {
                TimeLeft: '6:24 left in 1st Quarter.',
                SummaryEvent: '4th down and 17 at WL 15',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 46 yards to AY 39.',
              },
              6: {
                TimeLeft: '6:15 left in 1st Quarter.',
                SummaryEvent: '1st down and 10 at AY 41',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 41 yards to AY 0. FIRST DOWN. TOUCHDOWN. (Raul Ramirez PAT KICK GOOD.)',
              },
            },
          },
          4: {
            TeamName: 'Argyle',
            ScoreChange: true,
            AwayScorePrev: '7',
            HomeScorePrev: 0,
            AwayScoreCurr: '7',
            HomeScoreCurr: 0,
            Records: {
              1: {
                TimeLeft: '6:08 left in 1st Quarter.',
                SummaryEvent: '',
                SummaryType: 'Kickoff Return',
                SummaryDescription: 'Adam Schleder returns kick 25 yards.FUMBLE LOST.',
              },
            },
          },
          5: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: '7',
            HomeScorePrev: 0,
            AwayScoreCurr: '10',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 32',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for 12 yards to AY 20. FIRST DOWN.',
              },
              2: {
                RedZone: 1,
                SummaryEvent: '1st down and 10 at AY 20',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for 11 yards to AY 9. FIRST DOWN.',
              },
              3: {
                RedZone: 1,
                SummaryEvent: '1st down and G at AY 9',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -2 yards to AY 11.',
              },
              4: {
                RedZone: 1,
                SummaryEvent: '2nd down and G at AY 11',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 5 yards to AY 6.',
              },
              5: {
                RedZone: 1,
                SummaryEvent: '3rd down and G at AY 6',
                SummaryType: 'Run',
                SummaryDescription: 'Ara Rauls rush for 0 yards to AY 6.',
              },
              6: {
                TimeLeft: '3:41 left in 1st Quarter.',
                RedZone: 1,
                SummaryEvent: '4th down and G at AY 6',
                SummaryType: 'Field Goal',
                SummaryDescription: 'Ian Chavez 23-yard field goal. GOOD',
              },
            },
          },
          6: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '10',
            HomeScorePrev: 0,
            AwayScoreCurr: '10',
            HomeScoreCurr: 0,
            Records: {
              1: {
                TimeLeft: '3:34 left in 1st Quarter.',
                SummaryEvent: '',
                SummaryType: 'Kickoff Return',
                SummaryDescription: 'Adam Schleder returns kick 22 yards.',
              },
              2: {
                SummaryEvent: '1st down and 10 at AY 34',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 1 yards to AY 35.',
              },
              3: {
                SummaryEvent: '2nd down and 9 at AY 35',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 3 yards to AY 38.',
              },
              4: {
                SummaryEvent: '3rd down and 6 at AY 38',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              5: {
                TimeLeft: '2:22 left in 1st Quarter.',
                SummaryEvent: '4th down and 6 at AY 38',
                SummaryType: 'Punt',
                SummaryDescription: 'Alex Gonzales punts 41 yards to WL 21.',
              },
            },
          },
          7: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '10',
            HomeScorePrev: 0,
            AwayScoreCurr: '10',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 21',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 16 yards to WL 37. FIRST DOWN.',
              },
              2: {
                SummaryEvent: '1st down and 10 at WL 37',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 5 yards to WL 42.',
              },
              3: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 15 yards.',
              },
              4: {
                SummaryEvent: '2nd down and 20 at WL 27',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 10 yards to WL 37.',
              },
              5: {
                SummaryEvent: '',
                SummaryType: 'Penalty Defense',
                SummaryDescription: 'AY penalized 15 yards.FIRST DOWN.',
              },
              6: {
                SummaryEvent: '1st down and 10 at AY 48',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 11 yards to AY 37. FIRST DOWN.',
              },
              7: {
                SummaryEvent: '1st down and 10 at AY 37',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 31 yards to AY 6. FIRST DOWN.',
              },
              8: {
                RedZone: 1,
                SummaryEvent: '1st down and G at AY 6',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -2 yards to AY 8.',
              },
              9: {
                SummaryEvent: '',
                SummaryType: 'End of Quarter',
                SummaryDescription: 'End of 1st Quarter.',
              },
            },
          },
        },
      },
      '2nd Quarter': {
        BallPossession: {
          1: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: '10',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Start of Quarter',
                SummaryDescription: 'Start of 2nd Quarter',
              },
              2: {
                RedZone: 1,
                SummaryEvent: '2nd down and g at AY 8',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 6 yards to AY 2.',
              },
              3: {
                TimeLeft: '11:16 left in 2nd Quarter.',
                RedZone: 1,
                SummaryEvent: '3rd down and G at AY 2',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 2 yards to AY 0. TOUCHDOWN. (Ian Chavez PAT KICK GOOD.)',
              },
            },
          },
          2: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                TimeLeft: '11:09 left in 2nd Quarter.',
                SummaryEvent: '',
                SummaryType: 'Kickoff Return',
                SummaryDescription: 'Noah Lang returns kick 32 yards.',
              },
              2: {
                SummaryEvent: '1st down and 10 at WL 47',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Alex Gonzales for 13 yards to WL 34. FIRST DOWN.',
              },
              3: {
                SummaryEvent: '1st down and 10 at WL 34',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.FUMBLE HELD.',
              },
              4: {
                SummaryEvent: '2nd down and 10 at WL 34',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.FUMBLE HELD.',
              },
              5: {
                SummaryEvent: '',
                SummaryType: 'Penalty Defense',
                SummaryDescription: 'WL penalized 15 yards.FIRST DOWN.',
              },
              6: {
                TimeLeft: '10:28 left in 2nd Quarter.',
                RedZone: 1,
                SummaryEvent: '1st down and 10 at WL 19',
                SummaryType: 'Interception',
                SummaryDescription: 'Bo Hogeboom pass intercepted',
              },
            },
          },
          3: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 4',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 0 yards to WL 4.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at WL 4',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 6 yards to WL 10.',
              },
              3: {
                SummaryEvent: '3rd down and 4 at WL 10',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -1 yards to WL 9.',
              },
              4: {
                TimeLeft: '8:30 left in 2nd Quarter.',
                SummaryEvent: '4th down and 5 at WL 9',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 19 yards to WL 28.',
              },
            },
          },
          4: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 28',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at WL 28',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              3: {
                TimeLeft: '8:20 left in 2nd Quarter.',
                SummaryEvent: '',
                SummaryType: 'Timeout',
                SummaryDescription: 'Timeout.',
              },
              4: {
                SummaryEvent: '3rd down and 10 at WL 28',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              5: {
                TimeLeft: '8:09 left in 2nd Quarter.',
                SummaryEvent: '4th down and 10 at WL 28',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
            },
          },
          5: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 28',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 0 yards to WL 28.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at WL 28',
                SummaryType: 'Run',
                SummaryDescription: 'Ara Rauls rush for 10 yards to WL 38. FIRST DOWN.',
              },
              3: {
                SummaryEvent: '1st down and 10 at WL 38',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -1 yards to WL 37.',
              },
              4: {
                SummaryEvent: '2nd down and 11 at WL 37',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Ara Rauls pass incomplete.',
              },
              5: {
                SummaryEvent: '3rd down and 11 at WL 37',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -1 yards to WL 36.',
              },
              6: {
                TimeLeft: '5:15 left in 2nd Quarter.',
                SummaryEvent: '4th down and 12 at WL 36',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 14 yards to  50.',
              },
            },
          },
          6: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 50',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at WL 50',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 7 yards to WL 43.',
              },
              3: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'AY penalized 5 yards.',
              },
              4: {
                SummaryEvent: '3rd down and 8 at WL 48',
                SummaryType: 'Run',
                SummaryDescription: 'Bo Hogeboom rush for 4 yards to WL 44.',
              },
              5: {
                TimeLeft: '3:41 left in 2nd Quarter.',
                SummaryEvent: '4th down and 4 at WL 44',
                SummaryType: 'Run',
                SummaryDescription: 'Team Stat rush for -8 yards to AY 48.FUMBLE LOST.',
              },
            },
          },
          7: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 10 yards.',
              },
              2: {
                SummaryEvent: '1st down and 10 at AY 35',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 3 yards to AY 32.',
              },
              3: {
                SummaryEvent: '2nd down and 7 at AY 32',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 0 yards to AY 32.',
              },
              4: {
                SummaryEvent: '3rd down and 7 at AY 32',
                SummaryType: 'Run',
                SummaryDescription: 'Ara Rauls rush for 3 yards to AY 29.',
              },
              5: {
                TimeLeft: '2:08 left in 2nd Quarter.',
                SummaryEvent: '4th down and 4 at AY 29',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -1 yards to AY 30.',
              },
            },
          },
          8: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 30',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at AY 30',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 6 yards to AY 36.',
              },
              3: {
                TimeLeft: '1:23 left in 2nd Quarter.',
                SummaryEvent: '',
                SummaryType: 'Timeout',
                SummaryDescription: 'Timeout.',
              },
              4: {
                SummaryEvent: '3rd down and 4 at AY 36',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 2 yards to AY 38.',
              },
              5: {
                TimeLeft: ':22 left in 2nd Quarter.',
                SummaryEvent: '4th down and 2 at AY 38',
                SummaryType: 'Punt',
                SummaryDescription: 'Dillon Carter punts 56 yards to WL 6.',
              },
            },
          },
          9: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                TimeLeft: '8:25 left in 2nd Quarter.',
                SummaryEvent: '',
                SummaryType: 'End of Quarter',
                SummaryDescription: 'Halftime. Game is scheduled to resume at 8:25',
              },
            },
          },
        },
      },
      '3rd Quarter': {
        BallPossession: {
          1: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: 0,
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Start of Quarter',
                SummaryDescription: 'Start of 3rd Quarter',
              },
              2: {
                SummaryEvent: '1st down and 10 at WL 25',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -5 yards to WL 20.',
              },
              3: {
                SummaryEvent: '2nd down and 15 at WL 20',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -5 yards to WL 15.',
              },
              4: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 5 yards.',
              },
              5: {
                SummaryEvent: '3rd down and 25 at WL 10',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 1 yards to WL 11.',
              },
              6: {
                TimeLeft: '9:54 left in 3rd Quarter.',
                SummaryEvent: '4th down and 24 at WL 11',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 19 yards to WL 30.',
              },
            },
          },
          2: {
            TeamName: 'Argyle',
            ScoreChange: true,
            AwayScorePrev: '17',
            HomeScorePrev: 0,
            AwayScoreCurr: '17',
            HomeScoreCurr: '7',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 30',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 2 yards to WL 28.',
              },
              2: {
                SummaryEvent: '2nd down and 8 at WL 28',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 10 yards to WL 18. FIRST DOWN.',
              },
              3: {
                RedZone: 1,
                SummaryEvent: '1st down and 10 at WL 18',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              4: {
                RedZone: 1,
                SummaryEvent: '2nd down and 10 at WL 18',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 4 yards to WL 14.',
              },
              5: {
                RedZone: 1,
                SummaryEvent: '3rd down and 6 at WL 14',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 6 yards to WL 8. FIRST DOWN.',
              },
              6: {
                RedZone: 1,
                SummaryEvent: '1st down and G at WL 8',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 1 yards to WL 7.',
              },
              7: {
                TimeLeft: '8:07 left in 3rd Quarter.',
                RedZone: 1,
                SummaryEvent: '2nd down and G at WL 7',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Alex Gonzales for 7 yards to WL 0. TOUCHDOWN. (Grant Shaw PAT KICK GOOD.)',
              },
            },
          },
          3: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: '7',
            AwayScoreCurr: '17',
            HomeScoreCurr: '7',
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 5 yards.',
              },
              2: {
                SummaryEvent: '1st down and 15 at WL 11',
                SummaryType: 'Run',
                SummaryDescription: 'Ara Rauls rush for -1 yards to WL 10.',
              },
              3: {
                SummaryEvent: '2nd down and 16 at WL 10',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 4 yards to WL 14.',
              },
              4: {
                SummaryEvent: '3rd down and 12 at WL 14',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Ara Rauls pass incomplete.',
              },
              5: {
                TimeLeft: '6:47 left in 3rd Quarter.',
                SummaryEvent: '4th down and 12 at WL 14',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 40 yards to AY 46.',
              },
            },
          },
          4: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '17',
            HomeScorePrev: '7',
            AwayScoreCurr: '17',
            HomeScoreCurr: '7',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 46',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 1 yards to AY 47.',
              },
              2: {
                SummaryEvent: '2nd down and 9 at AY 47',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for -1 yards to AY 46.',
              },
              3: {
                SummaryEvent: '3rd down and 10 at AY 46',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              4: {
                TimeLeft: '5:42 left in 3rd Quarter.',
                SummaryEvent: '4th down and 10 at AY 46',
                SummaryType: 'Punt',
                SummaryDescription: 'Dillon Carter punts 54 yards to WL 0.',
              },
            },
          },
          5: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: '17',
            HomeScorePrev: '7',
            AwayScoreCurr: '24',
            HomeScoreCurr: '7',
            Records: {
              1: {
                TimeLeft: '5:30 left in 3rd Quarter.',
                SummaryEvent: '1st down and 10 at WL 20',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 80 yards to AY 0. FIRST DOWN. TOUCHDOWN. (Ian Chavez PAT KICK GOOD.)',
              },
            },
          },
          6: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '24',
            HomeScorePrev: '7',
            AwayScoreCurr: '24',
            HomeScoreCurr: '7',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 25',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at AY 25',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 1 yards to AY 26.',
              },
              3: {
                SummaryEvent: '3rd down and 9 at AY 26',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              4: {
                TimeLeft: '4:27 left in 3rd Quarter.',
                SummaryEvent: '4th down and 9 at AY 26',
                SummaryType: 'Punt',
                SummaryDescription: 'Dillon Carter punts 57 yards to WL 17.',
              },
            },
          },
          7: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '24',
            HomeScorePrev: '7',
            AwayScoreCurr: '24',
            HomeScoreCurr: '7',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 17',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for 1 yards to WL 18.',
              },
              2: {
                SummaryEvent: '2nd down and 9 at WL 18',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for 22 yards to WL 40. FIRST DOWN.',
              },
              3: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 5 yards.',
              },
              4: {
                SummaryEvent: '1st down and 15 at WL 35',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 5 yards to WL 40.',
              },
              5: {
                SummaryEvent: '2nd down and 10 at WL 40',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for 9 yards to WL 49.',
              },
              6: {
                SummaryEvent: '3rd down and 1 at WL 49',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for -1 yards to WL 48.',
              },
              7: {
                SummaryEvent: '4th down and 2 at WL 48',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -1 yards to WL 47.',
              },
            },
          },
          8: {
            TeamName: 'Argyle',
            ScoreChange: true,
            AwayScorePrev: '24',
            HomeScorePrev: '7',
            AwayScoreCurr: '24',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 47',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at WL 47',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Cole Kirkpatrick for 5 yards to WL 42.',
              },
              3: {
                SummaryEvent: '3rd down and 5 at WL 42',
                SummaryType: 'Run',
                SummaryDescription: 'Bo Hogeboom rush for 0 yards to WL 42.',
              },
              4: {
                SummaryEvent: '',
                SummaryType: 'Penalty Defense',
                SummaryDescription: 'WL penalized 15 yards.FIRST DOWN.',
              },
              5: {
                SummaryEvent: '1st down and 10 at WL 27',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Brandon White for 19 yards to WL 8. FIRST DOWN.',
              },
              6: {
                TimeLeft: ':19 left in 3rd Quarter.',
                RedZone: 1,
                SummaryEvent: '1st down and G at WL 8',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Brandon White for 8 yards to WL 0. TOUCHDOWN. (Grant Shaw PAT KICK GOOD.)',
              },
            },
          },
          9: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '24',
            HomeScorePrev: '14',
            AwayScoreCurr: '24',
            HomeScoreCurr: '14',
            Records: {
              1: {
                TimeLeft: ':07 left in 3rd Quarter.',
                SummaryEvent: '',
                SummaryType: 'Kickoff Return',
                SummaryDescription: 'Demicco Chambliss returns kick 41 yards.',
              },
              2: {
                SummaryEvent: '1st down and 10 at WL 43',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -2 yards to WL 41.',
              },
              3: {
                SummaryEvent: '2nd down and 12 at WL 41',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 53 yards to AY 6. FIRST DOWN.',
              },
              4: {
                SummaryEvent: '',
                SummaryType: 'End of Quarter',
                SummaryDescription: 'End of 3rd Quarter.',
              },
            },
          },
        },
      },
      '4th Quarter': {
        BallPossession: {
          1: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '24',
            HomeScorePrev: '14',
            AwayScoreCurr: '24',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Start of Quarter',
                SummaryDescription: 'Start of 4th Quarter',
              },
              2: {
                RedZone: 1,
                SummaryEvent: '1st down and g at AY 6',
                SummaryType: 'Run',
                SummaryDescription: 'Elisha Cummings rush for 1 yards to AY 5.',
              },
              3: {
                RedZone: 1,
                SummaryEvent: '2nd down and G at AY 5',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 0 yards to AY 5.',
              },
              4: {
                RedZone: 1,
                SummaryEvent: '3rd down and G at AY 5',
                SummaryType: 'Run',
                SummaryDescription: 'Team Stat rush for -16 yards to AY 21.FUMBLE HELD.',
              },
              5: {
                TimeLeft: '10:29 left in 4th Quarter.',
                SummaryEvent: '4th down and G at AY 21',
                SummaryType: 'Field Goal',
                SummaryDescription: 'Ian Chavez 38-yard field goal. MISSED',
              },
            },
          },
          2: {
            TeamName: 'Argyle',
            ScoreChange: true,
            AwayScorePrev: '24',
            HomeScorePrev: '14',
            AwayScoreCurr: '24',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'AY penalized 10 yards.',
              },
            },
          },
          3: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: '24',
            HomeScorePrev: '14',
            AwayScoreCurr: '24',
            HomeScoreCurr: '14',
            Records: {
              1: {
                TimeLeft: '10:23 left in 4th Quarter.',
                RedZone: 1,
                SummaryEvent: '',
                SummaryType: 'Timeout',
                SummaryDescription: 'Timeout.',
              },
            },
          },
          4: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '24',
            HomeScorePrev: '14',
            AwayScoreCurr: '24',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 20 at AY 11',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '',
                SummaryType: 'Penalty Defense',
                SummaryDescription: 'WL penalized 10 yards.',
              },
              3: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'AY penalized 10 yards.',
              },
              4: {
                SummaryEvent: '1st down and 20 at AY 11',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              5: {
                SummaryEvent: '2nd down and 20 at AY 11',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              6: {
                SummaryEvent: '3rd down and 20 at AY 11',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              7: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'AY penalized 5 yards.',
              },
              8: {
                TimeLeft: '9:40 left in 4th Quarter.',
                SummaryEvent: '4th down and 25 at AY 6',
                SummaryType: 'Punt',
                SummaryDescription: 'Dillon Carter punts 29 yards to AY 35.',
              },
            },
          },
          5: {
            TeamName: 'Waco La Vega',
            ScoreChange: true,
            AwayScorePrev: '24',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 35',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -1 yards to AY 36.',
              },
              2: {
                SummaryEvent: '2nd down and 11 at AY 36',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 1 yards to AY 35.',
              },
              3: {
                SummaryEvent: '3rd down and 10 at AY 35',
                SummaryType: 'Pass',
                SummaryDescription: 'Ara Rauls pass complete to Demicco Chambliss for 15 yards to AY 20. FIRST DOWN.',
              },
              4: {
                RedZone: 1,
                SummaryEvent: '1st down and 10 at AY 20',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for 3 yards to AY 17.',
              },
              5: {
                TimeLeft: '6:58 left in 4th Quarter.',
                RedZone: 1,
                SummaryEvent: '2nd down and 7 at AY 17',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 17 yards to AY 0. FIRST DOWN. TOUCHDOWN. (Ian Chavez PAT KICK GOOD.)',
              },
            },
          },
          6: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '31',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 32',
                SummaryType: 'Run',
                SummaryDescription: 'Tito Byce rush for 4 yards to AY 36.',
              },
              2: {
                SummaryEvent: '2nd down and 6 at AY 36',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Alex Gonzales for 5 yards to AY 41.',
              },
              3: {
                SummaryEvent: '3rd down and 1 at AY 41',
                SummaryType: 'Run',
                SummaryDescription: 'Luke Farris rush for 9 yards to  50. FIRST DOWN.',
              },
              4: {
                SummaryEvent: '1st down and 10 at WL 50',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Brandon White for 13 yards to WL 37. FIRST DOWN.',
              },
              5: {
                SummaryEvent: '1st down and 10 at WL 37',
                SummaryType: 'Run',
                SummaryDescription: 'Luke Farris rush for 3 yards to WL 34.',
              },
              6: {
                SummaryEvent: '2nd down and 7 at WL 34',
                SummaryType: 'Pass',
                SummaryDescription: 'Bo Hogeboom pass complete to Cole Kirkpatrick for 12 yards to WL 22. FIRST DOWN.',
              },
              7: {
                TimeLeft: '5:01 left in 4th Quarter.',
                SummaryEvent: '1st down and 10 at WL 22',
                SummaryType: 'Interception',
                SummaryDescription: 'Bo Hogeboom pass intercepted',
              },
            },
          },
          7: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '31',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at WL 5',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for 24 yards to WL 29. FIRST DOWN.',
              },
              2: {
                SummaryEvent: '1st down and 10 at WL 29',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -4 yards to WL 25.',
              },
              3: {
                SummaryEvent: '',
                SummaryType: 'Penalty Defense',
                SummaryDescription: 'AY penalized 5 yards.',
              },
              4: {
                SummaryEvent: '2nd down and 9 at WL 30',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -5 yards to WL 25.',
              },
            },
          },
          8: {
            TeamName: 'Argyle',
            ScoreChange: true,
            AwayScorePrev: '31',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                TimeLeft: '3:13 left in 4th Quarter.',
                SummaryEvent: '',
                SummaryType: 'Timeout',
                SummaryDescription: 'Timeout.',
              },
            },
          },
          9: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '31',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 5 yards.',
              },
              2: {
                SummaryEvent: '3rd down and 19 at WL 20',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -5 yards to WL 15.',
              },
              3: {
                TimeLeft: '2:39 left in 4th Quarter.',
                SummaryEvent: '4th down and 24 at WL 15',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 49 yards to AY 36.',
              },
            },
          },
          10: {
            TeamName: 'Argyle',
            ScoreChange: false,
            AwayScorePrev: '31',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 36',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              2: {
                SummaryEvent: '2nd down and 10 at AY 36',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              3: {
                SummaryEvent: '3rd down and 10 at AY 36',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
              4: {
                SummaryEvent: '4th down and 10 at AY 36',
                SummaryType: 'Incomplete Pass',
                SummaryDescription: 'Bo Hogeboom pass incomplete.',
              },
            },
          },
          11: {
            TeamName: 'Waco La Vega',
            ScoreChange: false,
            AwayScorePrev: '31',
            HomeScorePrev: '14',
            AwayScoreCurr: '31',
            HomeScoreCurr: '14',
            Records: {
              1: {
                SummaryEvent: '1st down and 10 at AY 36',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -2 yards to AY 38.',
              },
              2: {
                SummaryEvent: '',
                SummaryType: 'Penalty Offense',
                SummaryDescription: 'WL penalized 5 yards.',
              },
              3: {
                SummaryEvent: '2nd down and 17 at AY 43',
                SummaryType: 'Run',
                SummaryDescription: 'John Richards rush for -5 yards to AY 48.',
              },
              4: {
                SummaryEvent: '3rd down and 22 at AY 48',
                SummaryType: 'Run',
                SummaryDescription: 'Jar&#39;Quae Walton rush for -1 yards to AY 49.',
              },
              5: {
                TimeLeft: ':00 left in 4th Quarter.',
                SummaryEvent: '4th down and 23 at AY 49',
                SummaryType: 'Punt',
                SummaryDescription: 'Jacob Bryant punts 49 yards to AY 0.',
              },
            },
          },
        },
      },
    },
  },
  away: {
    id: '540',
    name: 'Waco La Vega',
    teamCode: 'WL',
    boxscore: [
      10,
      7,
      7,
      7,
      0,
      0,
      0,
      0,
    ],
    teamStats: {
      TotalYards: '344',
      FirstDowns: '14',
      RushingAttempts: '55',
      RushingYards: '329',
      PassCompletions: '1',
      PassAttempts: '4',
      PassingInterceptions: '0',
      PassingYards: '15',
      PassCompletionPercentage: 25,
      Punts: '7',
      PuntingYards: '236',
      PuntingAverage: '33.7143',
      Fumbles: '1',
      FumblesLost: '0',
      Penalties: '11',
      PenaltyYards: '95',
      AverageRush: 5.98,
    },
    playerStats: {
      Rushing: [{
        PlayerID: '15296',
        PlayerFirstName: 'John',
        PlayerLastName: 'Richards',
        PlayerNumber: '17',
        RushingAttempts: '19',
        RushingYards: '217',
        RushingYardsPerAttempt: '11.42',
        RushingTouchdowns: '4',
      },
      {
        PlayerID: '15292',
        PlayerFirstName: 'Jar&#39;Quae',
        PlayerLastName: 'Walton',
        PlayerNumber: '6',
        RushingAttempts: '24',
        RushingYards: '61',
        RushingYardsPerAttempt: '2.54',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '12314',
        PlayerFirstName: 'Elisha',
        PlayerLastName: 'Cummings',
        PlayerNumber: '',
        RushingAttempts: '7',
        RushingYards: '55',
        RushingYardsPerAttempt: '7.86',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '12297',
        PlayerFirstName: 'Ara',
        PlayerLastName: 'Rauls',
        PlayerNumber: '16',
        RushingAttempts: '4',
        RushingYards: '12',
        RushingYardsPerAttempt: '3.00',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '21937',
        PlayerFirstName: 'Team',
        PlayerLastName: 'Stat',
        PlayerNumber: '',
        RushingAttempts: '1',
        RushingYards: '-16',
        RushingYardsPerAttempt: '-16.00',
        RushingTouchdowns: '0',
      },
      ],
      Passing: [{
        PlayerID: '12297',
        PlayerFirstName: 'Ara',
        PlayerLastName: 'Rauls',
        PlayerNumber: '16',
        PassCompletions: '1',
        PassAttempts: '4',
        PassCompletionPercentage: 25,
        PassingYards: '15',
        PassingTouchdowns: '0',
        PassingInterceptions: '0',
      }],
      Receiving: [{
        PlayerID: '12280',
        PlayerFirstName: 'Demicco',
        PlayerLastName: 'Chambliss',
        PlayerNumber: '2',
        Receptions: '1',
        ReceivingYards: '15',
        YardsPerCatch: '15.0',
        ReceivingTouchdowns: '0',
      }],
    },
  },
  home: {
    id: '881',
    name: 'Argyle',
    teamCode: 'AY',
    boxscore: [
      0,
      0,
      14,
      0,
      0,
      0,
      0,
      0,
    ],
    teamStats: {
      TotalYards: '199',
      FirstDowns: '13',
      RushingAttempts: '25',
      RushingYards: '70',
      PassCompletions: '11',
      PassAttempts: '38',
      PassingInterceptions: '2',
      PassingYards: '129',
      PassCompletionPercentage: 28.95,
      Punts: '5',
      PuntingYards: '237',
      PuntingAverage: '47.4',
      Fumbles: '4',
      FumblesLost: '2',
      Penalties: '7',
      PenaltyYards: '55',
      AverageRush: 2.8,
    },
    playerStats: {
      Rushing: [{
        PlayerID: '3024',
        PlayerFirstName: 'Tito',
        PlayerLastName: 'Byce',
        PlayerNumber: '9',
        RushingAttempts: '19',
        RushingYards: '61',
        RushingYardsPerAttempt: '3.21',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '3040',
        PlayerFirstName: 'Luke',
        PlayerLastName: 'Farris',
        PlayerNumber: '26',
        RushingAttempts: '2',
        RushingYards: '12',
        RushingYardsPerAttempt: '6.00',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '3027',
        PlayerFirstName: 'Bo',
        PlayerLastName: 'Hogeboom',
        PlayerNumber: '13',
        RushingAttempts: '2',
        RushingYards: '4',
        RushingYardsPerAttempt: '2.00',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '3021',
        PlayerFirstName: 'Alex',
        PlayerLastName: 'Gonzales',
        PlayerNumber: '6',
        RushingAttempts: '1',
        RushingYards: '1',
        RushingYardsPerAttempt: '1.00',
        RushingTouchdowns: '0',
      },
      {
        PlayerID: '15301',
        PlayerFirstName: 'Team',
        PlayerLastName: 'Stat',
        PlayerNumber: '',
        RushingAttempts: '1',
        RushingYards: '-8',
        RushingYardsPerAttempt: '-8.00',
        RushingTouchdowns: '0',
      },
      ],
      Passing: [{
        PlayerID: '3027',
        PlayerFirstName: 'Bo',
        PlayerLastName: 'Hogeboom',
        PlayerNumber: '13',
        PassCompletions: '11',
        PassAttempts: '38',
        PassCompletionPercentage: 28.95,
        PassingYards: '129',
        PassingTouchdowns: '2',
        PassingInterceptions: '2',
      }],
      Receiving: [{
        PlayerID: '3021',
        PlayerFirstName: 'Alex',
        PlayerLastName: 'Gonzales',
        PlayerNumber: '6',
        Receptions: '4',
        ReceivingYards: '52',
        YardsPerCatch: '13.0',
        ReceivingTouchdowns: '1',
      },
      {
        PlayerID: '3026',
        PlayerFirstName: 'Brandon',
        PlayerLastName: 'White',
        PlayerNumber: '11',
        Receptions: '3',
        ReceivingYards: '40',
        YardsPerCatch: '13.3',
        ReceivingTouchdowns: '1',
      },
      {
        PlayerID: '3038',
        PlayerFirstName: 'Cole',
        PlayerLastName: 'Kirkpatrick',
        PlayerNumber: '24',
        Receptions: '3',
        ReceivingYards: '37',
        YardsPerCatch: '12.3',
        ReceivingTouchdowns: '0',
      },
      {
        PlayerID: '3018',
        PlayerFirstName: 'Dillon',
        PlayerLastName: 'Carter',
        PlayerNumber: '3',
        Receptions: '1',
        ReceivingYards: '0',
        YardsPerCatch: '0.0',
        ReceivingTouchdowns: '0',
      },
      ],
    },
  },
};
